In [13]:
import pandas as pd
import sklearn
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
data = pd.read_csv('/content/emvic.data',sep='\t', header=None)
data

0      1      2      3      4      5      6      7      8      9      ...  \
0     a25      0      0      0      0      0      0      0      0      0  ...   
1     a25      0      0      0      0      0      0      0      0      0  ...   
2     a25      0      0      0      0      0      0      0      0      0  ...   
3     a25      0      0      0      0      0      0      0      0      0  ...   
4     a25      0      0      0      0      0      0      0      0      0  ...   
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  ...   
411   a41      0      0      0      0      0      0      0      0      0  ...   
412   a41      0      0      0      0      0      0      0      0      0  ...   
413   a41      0      0      0      0      0      0      0      0      0  ...   
414   a41      0      0      0      0      0      0      0      0      0  ...   
415   a41      0      0      0      0      0      0      0      0      0  ...   

     12279  12280  12281  12282  12283  12284  12285  12286  12287  12288  
0      -20    -20    -20    -20    -19    -20    -22    -19    -22    -23  
1      -74    -73    -75    -73    -72    -72    -69    -67    -67    -70  
2      -51    -52    -54    -51    -54    -54    -54    -53    -52    -54  
3       74     74     74     74     74     74     75     71     76     74  
4      129    130    130    133    131    129    124    124    122    117  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
411     83     81     80     82     80     82     82     80     81     79  
412      9      9      8     11      8      9     12     10     15     12  
413    223    223    222    223    225    227    230    229    227    226  
414    440    438    440    440    439    441    442    446    445    445  
415    613    612    610    600    589    581    575    575    577    578  

[416 rows x 12289 columns]

KNeighborsClassifier


In [14]:
model = KNeighborsClassifier()

In [15]:
from collections import Counter
samples = data.values[:,4096:]
labels = data.values[:,0]
model.fit(samples, labels)

print("Labels distribution:",Counter(labels))
# train-test split
(trainSamples, testSamples, trainLabels, testLabels) = sklearn.model_selection.train_test_split(samples, labels, random_state=30
    , stratify=labels
    #, train_size=0.5
    )

print("Train labels distribution:", Counter(trainLabels))
print("Test labels distribution:",Counter(testLabels))

model = KNeighborsClassifier()
model.fit(trainSamples, trainLabels)

Labels distribution: Counter({'a25': 105, 'a37': 63, 'a40': 52, 'a32': 50, 'a41': 39, 'a42': 38, 'a29': 36, 'a28': 33})
Train labels distribution: Counter({'a25': 79, 'a37': 47, 'a40': 39, 'a32': 38, 'a41': 29, 'a42': 28, 'a29': 27, 'a28': 25})
Test labels distribution: Counter({'a25': 26, 'a37': 16, 'a40': 13, 'a32': 12, 'a41': 10, 'a42': 10, 'a29': 9, 'a28': 8})


KNeighborsClassifier()

In [16]:
sklearn.model_selection.cross_validate(model, samples, labels, cv=10)

{'fit_time': array([0.752985  , 0.59276724, 0.69585395, 0.92665458, 1.12766623,
        0.59527326, 0.60824251, 0.60548997, 0.58853531, 0.61828566]),
 'score_time': array([0.05021381, 0.04937363, 0.24912024, 0.17241836, 0.05852509,
        0.04568172, 0.04312873, 0.05778003, 0.04497099, 0.04601073]),
 'test_score': array([0.57142857, 0.73809524, 0.66666667, 0.76190476, 0.69047619,
        0.64285714, 0.6097561 , 0.75609756, 0.80487805, 0.7804878 ])}

In [17]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score,cohen_kappa_score
modelResults = model.predict(testSamples)
print(confusion_matrix(testLabels, modelResults))
print(classification_report(testLabels, modelResults))
accuracy = accuracy_score(testLabels, modelResults)
print("Accuracy: {:.2f}".format(accuracy))
print("Cohen's Kappa: {:.2f}".format(cohen_kappa_score(testLabels, modelResults)))

[[25  0  0  1  0  0  0  0]
 [ 0  7  0  0  0  0  0  1]
 [ 0  0  9  0  0  0  0  0]
 [ 4  0  2  4  1  0  0  1]
 [ 1  2  1  0 10  0  2  0]
 [ 1  2  0  0  0 10  0  0]
 [ 0  2  0  0  2  0  6  0]
 [ 0  1  1  0  0  0  0  8]]
              precision    recall  f1-score   support

         a25       0.81      0.96      0.88        26
         a28       0.50      0.88      0.64         8
         a29       0.69      1.00      0.82         9
         a32       0.80      0.33      0.47        12
         a37       0.77      0.62      0.69        16
         a40       1.00      0.77      0.87        13
         a41       0.75      0.60      0.67        10
         a42       0.80      0.80      0.80        10

    accuracy                           0.76       104
   macro avg       0.76      0.75      0.73       104
weighted avg       0.78      0.76      0.75       104

Accuracy: 0.76
Cohen's Kappa: 0.72


GaussianNB

In [18]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

Gau = GaussianNB()
Gau.fit(trainSamples, trainLabels)

modelResults = Gau.predict(testSamples)
print(confusion_matrix(testLabels, modelResults))
print(classification_report(testLabels, modelResults))
accuracy = accuracy_score(testLabels, modelResults)
print("Accuracy: {:.2f}".format(accuracy))
print("Cohen's Kappa: {:.2f}".format(cohen_kappa_score(testLabels, modelResults)))



[[17  0  0  7  1  0  0  1]
 [ 0  1  2  1  0  3  1  0]
 [ 0  0  9  0  0  0  0  0]
 [ 2  0  0  9  1  0  0  0]
 [ 0  2  0  5  6  1  0  2]
 [ 0  0  0  0  1 11  1  0]
 [ 0  2  0  1  1  0  5  1]
 [ 4  1  0  1  0  0  0  4]]
              precision    recall  f1-score   support

         a25       0.74      0.65      0.69        26
         a28       0.17      0.12      0.14         8
         a29       0.82      1.00      0.90         9
         a32       0.38      0.75      0.50        12
         a37       0.60      0.38      0.46        16
         a40       0.73      0.85      0.79        13
         a41       0.71      0.50      0.59        10
         a42       0.50      0.40      0.44        10

    accuracy                           0.60       104
   macro avg       0.58      0.58      0.56       104
weighted avg       0.61      0.60      0.59       104

Accuracy: 0.60
Cohen's Kappa: 0.53


Linear Discriminant Analysis

In [19]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

LDA = LinearDiscriminantAnalysis()
LDA.fit(trainSamples, trainLabels)

modelResults = LDA.predict(testSamples)
print(confusion_matrix(testLabels, modelResults))
print(classification_report(testLabels, modelResults))
accuracy = accuracy_score(testLabels, modelResults)
print("Accuracy: {:.2f}".format(accuracy))
print("Cohen's Kappa: {:.2f}".format(cohen_kappa_score(testLabels, modelResults)))


[[25  1  0  0  0  0  0  0]
 [ 0  7  0  0  0  0  0  1]
 [ 0  0  9  0  0  0  0  0]
 [ 1  0  0 10  1  0  0  0]
 [ 0  0  1  1 12  0  1  1]
 [ 1  0  0  0  0 12  0  0]
 [ 1  0  0  1  0  0  8  0]
 [ 0  0  0  0  0  0  0 10]]
              precision    recall  f1-score   support

         a25       0.89      0.96      0.93        26
         a28       0.88      0.88      0.88         8
         a29       0.90      1.00      0.95         9
         a32       0.83      0.83      0.83        12
         a37       0.92      0.75      0.83        16
         a40       1.00      0.92      0.96        13
         a41       0.89      0.80      0.84        10
         a42       0.83      1.00      0.91        10

    accuracy                           0.89       104
   macro avg       0.89      0.89      0.89       104
weighted avg       0.90      0.89      0.89       104

Accuracy: 0.89
Cohen's Kappa: 0.88
